<meta name="apple-mobile-web-app-title" content="Avida Land PWA" />

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link href="https://geistsans.com/font.css" rel="stylesheet" />
      <body
        className={`antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
